name: bip_topl
description: SDK for the cryptography components for building Topl blockchain mobile apps using Flutter
version: 0.0.1
homepage: https://github.com/Topl/bip-topl
repository: https://github.com/Topl/bip-topl
issue_tracker: https://github.com/Topl/bip-topl/issues

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies: 
  crypto: ^3.0.1
  fast_base58: ^0.2.0
  pinenacl: ^0.3.3
  pointycastle: ^3.3.1
  unorm_dart: ^0.2.0
