name: bip_topl
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies: 
  fast_base58: ^0.2.0
  pinenacl: ^0.3.3
  pointycastle: ^3.3.1
  unorm_dart: ^0.2.0
