name: Dart CI
#set conditions to trigger on
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    - cron: "0 0 * * 0"
# define what happens when conditions are met
jobs:
  # Check code formatting and static analysis on three OS (linux, macOS, and windows)
  # against dev, beta, stable, and 2.13.0 (The package's lower bound)
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - name: Analyze Dart
        run: dart analyze --fatal-warnings --fatal-infos .
  # Run tests on a matrix consisting of two dimensions:
  # 1. OS: ubuntu-latest, macos-latest, windows-latest
  # 2. Release channel: dev, stable, and 2.13.0 (the package's lower bound)
  dart_tests:
    name: 'Dart tests | Dart ${{ matrix.dart_channel }} | ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dart_channel: [stable]
        include: [{os: ubuntu-latest, dart_channel: dev}]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with: {sdk: "${{matrix.dart_channel }}"}
      - id: install
        name: Install dependencies
        run: dart pub get
      - run: dart pub run grinder pkg-standalone-dev
      - name: Run tests
        run: dart pub run test -p vm -x node -r expanded