
name: Update Dart Documentation
on: 
  workflow_dispatch:
jobs:
    dartdoc:
        name: Dartdoc
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v2
          - uses: dart-lang/setup-dart@v1
          - run: dart pub get
          - uses: subosito/flutter-action@v1
            with:
                channel: 'stable'
          - uses: flame-engine/flame-dartdoc-action@v1
          - name: Copy directory
            run: |
                rm -rf docs/ | mv doc/ docs/
          - name: deploy
            uses: peaceiris/actions-gh-pages@v3
                with: github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./docs

