
name: Pre-release sanity check
on: 
  workflow_dispatch:
jobs:
    sanity_checks:
        name: Sanity checks
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - uses: dart-lang/setup-dart@v1
        - run: dart pub get
        - name: Run checks
          run: dart pub run grinder sanity-check-before-release

