
name: Update Dart Documentation
on: 
  workflow_dispatch:
jobs:
    sanity_checks:
        name: Sanity checks
        runs-on: ubuntu-latest
        if: "startsWith(github.ref, 'refs/tags/') && github.repository == 'Topl/bip-topl'"

        steps:
        - uses: actions/checkout@v2
        - uses: dart-lang/setup-dart@v1
        - run: dart pub get
        - name: Run checks
          run: dart pub run grinder sanity-check-before-release

